# managed by saltstack

global:
  scrape_interval:     15s # By default, scrape targets every 15 seconds.
  evaluation_interval: 15s
  scrape_timeout:      15s

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 20s
    static_configs:
      - targets:
        - bunker.imagilan:9090

  - job_name: 'node'
    scrape_interval: 15s
    static_configs:
    - targets:
      - bunker.imagilan:9100
      - f17gw.imagilan:9100
      - furrow-vpn.imagilan:9100
      - pi02.imagilan:9100
      - repeater-bedroom1.imagilan:9100
      - repeater-hof-north.imagilan:9100
      - repeater-lounge.imagilan:9100
      - repeater-street-north.imagilan:9100
      - repeater-street-south.imagilan:9100

  - job_name: 'snmp-edgeswitch'
    scrape_interval: 20s
    scrape_timeout: 20s
    static_configs:
    - targets:
      - switch01.imagilan
    metrics_path: /snmp
    params:
      module: [edgeswitch]
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: 127.0.0.1:9116

  - job_name: 'snmp-AirOS'
    scrape_interval: 90s
    scrape_timeout: 90s
    static_configs:
    - targets:
      - emmauskirche.imagilan
    metrics_path: /snmp
    params:
      module: [ubiquiti_airmax]
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: 127.0.0.1:9116

  - job_name: 'openhab'
    scrape_interval: 10s
    static_configs:
      - targets:
        - bunker.imagilan:9997