# managed by saltstack

global:
  scrape_interval:     15s # By default, scrape targets every 15 seconds.
  evaluation_interval: 15s # By default, scrape targets every 15 seconds.
  scrape_timeout:      9s

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 30s
    target_groups:
      - targets: ['bunker.imagilan:9090']

  - job_name: node
    scrape_interval: 30s
    target_groups:
      - targets: ['imagiswitch.imagilan:9100']
      - targets: ['repeater01.imagilan:9100']
      - targets: ['repeater04.imagilan:9100']
      - targets: ['repeater05.imagilan:9100']
      - targets: ['repeater06.imagilan:9100']
      - targets: ['bunker.imagilan:9100']
      - targets: ['pi02.imagilan:9100']
