# managed by saltstack

global:
  scrape_interval:     15s # By default, scrape targets every 15 seconds.
  evaluation_interval: 15s
  scrape_timeout:      15s

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 20s
    static_configs:
      - targets:
        - bunker.imagilan:9090

  - job_name: 'node'
    scrape_interval: 15s
    static_configs:
    - targets:
      - bunker.imagilan:9100
      - f17-core.imagilan:9100
      - f17gw.imagilan:9100
      - furrow-vpn.imagilan:9100
      - ln.imagilan:9100
      - pi02.imagilan:9100
      - repeater-bedroom1.imagilan:9100
      - repeater-hof-north.imagilan:9100
      - repeater-lounge.imagilan:9100
      - repeater-street-north.imagilan:9100
      - repeater-street-south.imagilan:9100
      - switch02.imagilan:9100

  - job_name: 'snmp-edgeswitch'
    scrape_interval: 20s
    scrape_timeout: 20s
    static_configs:
    - targets:
      - switch01.imagilan
    metrics_path: /snmp
    params:
      module: [edgeswitch]
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: 127.0.0.1:9116

  - job_name: 'snmp-AirOS'
    scrape_interval: 90s
    scrape_timeout: 90s
    static_configs:
    - targets:
      - emma-bridge.imagilan
      - zwingli-bridge.imagilan
      - rhnk-bridge.imagilan
    metrics_path: /snmp
    params:
      module: [ubiquiti_airmax]
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: 127.0.0.1:9116

  - job_name: 'openhab-server-metrics'
    scrape_interval: 1m
    scheme: http
    metrics_path: /rest/metrics/prometheus
    static_configs:
    - targets:
      - 'bunker.imagilan:8080'

  - job_name: 'openhab'
    scrape_interval: 10s
    static_configs:
      - targets:
        - bunker.imagilan:9997

  - job_name: 'blackbox-web'
    scrape_interval: 60s
    metrics_path: /probe
    params:
      module: [http_2xx]  # Look for a HTTP 200 response.
    static_configs:
      - targets:
        - https://bunker.imaginator.com 
        - http://bunker.imagilan
        - http://openhab.imagilan
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: 127.0.0.1:9115  # The blackbox exporter's real hostname:port.

# to get hostnames
# grep "uci set .*dhcp.@.*\[-1\].name=" ~/Documents/src/home-network/f17gw.settings | sed -e "s/uci set.*dhcp.\@\(host\|domain\)\[-1\].name='/        - /" | sed -e "s/'$/.imagilan/" | sort
  - job_name: 'blackbox-ping'
    scrape_interval: 120s
    metrics_path: /probe
    params:
      module: [icmp]
    static_configs:
      - targets:
        - 2001:4860:4860::8888
        - 2001:4860:4860::8844
        - 8.8.8.8
        - 8.8.4.4
        - 2606:4700:4700::1111
        - 2606:4700:4700::1001
        - 1.1.1.1
        - 1.0.0.1
        - android-vpn.imagilan
        - bathroom-scale.imagilan
        - brother-printer.imagilan
        - bunker.imagilan
        - bunker-iot.imagilan
        - camera01.imagilan
        - camera02.imagilan
        - cca-bedroom1.imagilan
        - cca-bedroom2.imagilan
        - cca-bedroom3.imagilan
        - cca-guestbath.imagilan
        - cca-kitchen.imagilan
        - cca-mainbath.imagilan
        - cca-study.imagilan
        - cca-terrace.imagilan
        - ccmini-bedroom1.imagilan
        - ccmini-guestbath.imagilan
        - ccmini-kitchen.imagilan
        - ccmini-lounge.imagilan
        - ccmini-mainbath.imagilan
        - ccmini-study.imagilan
        - coffeemachine.imagilan
        - doorbird.imagilan
        - emma-bridge.imagilan
        - f17-core.imagilan
        - f17gw.imagilan
        - f17gw-vpn.imagilan
        - furrow.imagilan
        - furrow-vpn.imagilan
        - gruenbeck.imagilan
        - hue.imagilan
        - ilo.imagilan
        - imagisuck.imagilan
        - irrigation.imagilan
        - knxrouter.imagilan
        - ln2.imagilan
        - ln.imagilan
        - nvidia-shield.imagilan
        - onkyo-receiver.imagilan
        - oven.imagilan
        - pi01.imagilan
        - pi02.imagilan
        - plugswitch04.imagilan
        - plugswitch05.imagilan
        - plugswitch06.imagilan
        - plugswitch07.imagilan
        - plugswitch08.imagilan
        - plugswitch09.imagilan
        - plugswitch-hifi.imagilan
        - plugswitch-laptop.imagilan
        - plugswitch-ventilation.imagilan
        - projector01.imagilan
        - repeater08.imagilan
        - repeater-bedroom1.imagilan
        - repeater-hof-north.imagilan
        - repeater-lounge.imagilan
        - repeater-street-north.imagilan
        - repeater-street-south.imagilan
        - rhnk-bridge.imagilan
        - simon-phone.imagilan
        - stove.imagilan
        - switch01.imagilan
        - switch02.imagilan
        - tablet-bathroomguest.imagilan
        - tablet-bathroommain.imagilan
        - tablet-bedroom1.imagilan
        - tablet-bedroom2.imagilan
        - tablet-bedroom3.imagilan
        - tablet-hallwaylarge.imagilan
        - tablet-kitchen.imagilan
        - tablet-lounge.imagilan
        - tablet-study.imagilan
        - vallox.imagilan
        - veluxgw.imagilan
        - w16gw.imagilan
        - washing-machine.imagilan
        - waterlogger.imagilan
        - win10.imagilan
        - wolliner-vpn.imagilan
        - zwingli-bridge.imagilan

    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: 127.0.0.1:9115  # This is your blackbox exporter.

