# managed by saltstack

global:
  scrape_interval:     15s # By default, scrape targets every 15 seconds.
  evaluation_interval: 15s # By default, scrape targets every 15 seconds.
  scrape_timeout:      9s

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 30s
    target_groups:
      - targets: ['bunker.imagilan:9090']

  - job_name: 'node'
    scrape_interval: 30s
    target_groups:
      - targets: ['imagiswitch.imagilan:9100']
      - targets: ['repeater01.imagilan:9100']
      - targets: ['repeater04.imagilan:9100']
      - targets: ['repeater05.imagilan:9100']
      - targets: ['repeater06.imagilan:9100']
      - targets: ['bunker.imagilan:9100']
      - targets: ['pi02.imagilan:9100']

  - job_name: 'snmp'
    scrape_interval: 10s
    target_groups:
      - targets:
        - 10.7.11.2
    metrics_path: /snmp
    params:
      module: [edgeswitch]
    relabel_configs:
      - source_labels: [__address__]
        regex: (.*?)(:80)?
        target_label: __param_target
        replacement: ${1}
      - source_labels: [__param_address]
        regex: (.*)
        target_label: instance
        replacement: ${1}
      - source_labels: []
        regex: .*
        target_label: __address__
        replacement: 127.0.0.1:9116  # SNMP exporter.
