openvpn-client:
  server: vpn03.berlin.freifunk.net 1194

openvpn-certificates:
  vpn03.berlin.freifunk.net:
    key: |
      -----BEGIN RSA PRIVATE KEY-----
      MIICXgIBAAKBgQDLCBDd6EPCN24AB4fFyKKJnJ5yefxAfyoW4gxqTKEHVwrDwEL2
      8G/TMqaV5H/lBTb40pFIyiOnTcVF/yIgjaNKvHdxUPzYlVu7PQ2XMecD61MiBYRl
      QnGVO3Zkv8d6MAuGpQulma2AZNnhOdgPvSc5nLE9vXTiCWrlAP4DN+rwhQIDAQAB
      AoGAWmhyEk599br3CZ5Q0DrCXeLXD4TQVewKUvw/qQoMXpdc3MP9TbbNJM+WLIL+
      jH3g97XUKgSREcvov32XtcU8Y50rdhabtSkqnzhe6fh+pE5dZeaJ5qQE6R4Q3O5p
      KESCbJTmRbv+NVhSZOKeJJ2sKA86FmUiwjBvfKiUjSO38EECQQDoS4WzbzMug9ag
      HpT0GTxn7dyuCkrXGXiZAWaM93em8m0aWYdTinrIJI3ItSAuMSr2bdyffdIndMAC
      fOGjyXuVAkEA38AQQ+TlkBwce8GBE1UDiGX6pY9xyFwuVBGKzmDlFw/PJoJoyHCk
      +PxV2G3iN63xbQFsnZCJwygBSmQh9BblMQJBAOB50rsB82C40FetFd4I4QHBryaU
      FZxlJdAdtV716S9wR5RV/dryEBKGmGji9zUMGGtI4RFTAhlUzhPZYCbplj0CQQDU
      vWC5rSE37AKJCGsZXnOFdLDkSYb94eeKt0MrBqXLT5S+ILBQJAo3UnSs242DMzeh
      VQFYrtzNWXQgryQ5WKuBAkEAzEySnEfmUrySnimKk/B14nK6I+3tXWbws6yHwPQN
      TJlOmV47eD8daiJ0I2peW4hdPRVc2V1f0ZPBq6lhr6m5og==
      -----END RSA PRIVATE KEY-----
    cert: |
      -----BEGIN CERTIFICATE-----
      MIIEPTCCA6agAwIBAgICAeEwDQYJKoZIhvcNAQEFBQAwga4xCzAJBgNVBAYTAkRF
      MRgwFgYDVQQIEw9FYXN0ZXJuIEdlcm1hbnkxDzANBgNVBAcTBkJlcmxpbjErMCkG
      A1UEChMiRm9lcmRlcnZlcmVpbiBGcmVpZSBOZXR6d2Vya2UgZS5WLjERMA8GA1UE
      CxMIRnJlaWZ1bmsxFDASBgNVBAMTCzc3Ljg3LjQ4LjEwMR4wHAYJKoZIhvcNAQkB
      Fg9zdmVuLW9sYUBnbXguZGUwHhcNMTUwNjE2MTcyNDEyWhcNMjUwNjEzMTcyNDEy
      WjCBrzELMAkGA1UEBhMCREUxGDAWBgNVBAgTD0Vhc3Rlcm4gR2VybWFueTEPMA0G
      A1UEBxMGQmVybGluMSswKQYDVQQKEyJGb2VyZGVydmVyZWluIEZyZWllIE5ldHp3
      ZXJrZSBlLlYuMSMwIQYDVQQDFBpmcmVpZnVua19iZXJsaW4taW1hZ2luYXRvcjEj
      MCEGCSqGSIb3DQEJARYUc2ltb25AaW1hZ2luYXRvci5jb20wgZ8wDQYJKoZIhvcN
      AQEBBQADgY0AMIGJAoGBAMsIEN3oQ8I3bgAHh8XIoomcnnJ5/EB/KhbiDGpMoQdX
      CsPAQvbwb9MyppXkf+UFNvjSkUjKI6dNxUX/IiCNo0q8d3FQ/NiVW7s9DZcx5wPr
      UyIFhGVCcZU7dmS/x3owC4alC6WZrYBk2eE52A+9JzmcsT29dOIJauUA/gM36vCF
      AgMBAAGjggFlMIIBYTAJBgNVHRMEAjAAMC0GCWCGSAGG+EIBDQQgFh5FYXN5LVJT
      QSBHZW5lcmF0ZWQgQ2VydGlmaWNhdGUwHQYDVR0OBBYEFJIKqLYkuREmLx/HZp5u
      Vw0/ioBaMIHjBgNVHSMEgdswgdiAFAJCzLVTU1sOWG/esqwRY8b24KcNoYG0pIGx
      MIGuMQswCQYDVQQGEwJERTEYMBYGA1UECBMPRWFzdGVybiBHZXJtYW55MQ8wDQYD
      VQQHEwZCZXJsaW4xKzApBgNVBAoTIkZvZXJkZXJ2ZXJlaW4gRnJlaWUgTmV0endl
      cmtlIGUuVi4xETAPBgNVBAsTCEZyZWlmdW5rMRQwEgYDVQQDEws3Ny44Ny40OC4x
      MDEeMBwGCSqGSIb3DQEJARYPc3Zlbi1vbGFAZ214LmRlggkAxO81HMAuzvIwEwYD
      VR0lBAwwCgYIKwYBBQUHAwIwCwYDVR0PBAQDAgeAMA0GCSqGSIb3DQEBBQUAA4GB
      AFzpS4RhzoaccvZMJQz7rmj1UTPQ4PHwAOlZ/03bYhkVHLuQj/DkoqIcd++Ohi27
      1yjHE/F00aJPhqDzv5msaEQC0CDSE8cDv4bDdZKRomjx//xM7bwdYA57gHvyfz3p
      HlGpdTsqGuz9ylVgP84n1U18OMMjLplR50bIfcfuRbwo
      -----END CERTIFICATE-----
    ca: |
      -----BEGIN CERTIFICATE-----
      MIID9TCCA16gAwIBAgIJAMTvNRzALs7yMA0GCSqGSIb3DQEBBQUAMIGuMQswCQYD
      VQQGEwJERTEYMBYGA1UECBMPRWFzdGVybiBHZXJtYW55MQ8wDQYDVQQHEwZCZXJs
      aW4xKzApBgNVBAoTIkZvZXJkZXJ2ZXJlaW4gRnJlaWUgTmV0endlcmtlIGUuVi4x
      ETAPBgNVBAsTCEZyZWlmdW5rMRQwEgYDVQQDEws3Ny44Ny40OC4xMDEeMBwGCSqG
      SIb3DQEJARYPc3Zlbi1vbGFAZ214LmRlMB4XDTEyMTEyODIxMDAxNFoXDTIyMTEy
      NjIxMDAxNFowga4xCzAJBgNVBAYTAkRFMRgwFgYDVQQIEw9FYXN0ZXJuIEdlcm1h
      bnkxDzANBgNVBAcTBkJlcmxpbjErMCkGA1UEChMiRm9lcmRlcnZlcmVpbiBGcmVp
      ZSBOZXR6d2Vya2UgZS5WLjERMA8GA1UECxMIRnJlaWZ1bmsxFDASBgNVBAMTCzc3
      Ljg3LjQ4LjEwMR4wHAYJKoZIhvcNAQkBFg9zdmVuLW9sYUBnbXguZGUwgZ8wDQYJ
      KoZIhvcNAQEBBQADgY0AMIGJAoGBALW3/1zuwC7/tHjRsATFJw1NgySvFS/knY7V
      VOX7Iy3NC0GWVhY3EpSjvaKAo5fjvcN21faRRRmlIJ99lQk3UKHJMORwdrF4D8T3
      O3af67WpNnn79VQlLk+xSbGKT9rGGrhiM0wJssjCVcGxvwKSaLpBoqmD4VHAmJ2u
      mURQgjHDAgMBAAGjggEXMIIBEzAdBgNVHQ4EFgQUAkLMtVNTWw5Yb96yrBFjxvbg
      pw0wgeMGA1UdIwSB2zCB2IAUAkLMtVNTWw5Yb96yrBFjxvbgpw2hgbSkgbEwga4x
      CzAJBgNVBAYTAkRFMRgwFgYDVQQIEw9FYXN0ZXJuIEdlcm1hbnkxDzANBgNVBAcT
      BkJlcmxpbjErMCkGA1UEChMiRm9lcmRlcnZlcmVpbiBGcmVpZSBOZXR6d2Vya2Ug
      ZS5WLjERMA8GA1UECxMIRnJlaWZ1bmsxFDASBgNVBAMTCzc3Ljg3LjQ4LjEwMR4w
      HAYJKoZIhvcNAQkBFg9zdmVuLW9sYUBnbXguZGWCCQDE7zUcwC7O8jAMBgNVHRME
      BTADAQH/MA0GCSqGSIb3DQEBBQUAA4GBALNbidmOZgUosAl3z700RQaglGHpZkj7
      S4zvnLiDDgFaXoj1lhy0r6V50QXZqM3St841fqNLATECp96h/2GS7cV1m51mEYly
      CGJM+gVirwVla/Bg97O608TITvwA9YGH3Q6kn0lXkRSS6RxeMcBexrIzsFa/E8Oy
      QoM7a8APavQi
      -----END CERTIFICATE-----    
