{
 "title": "OpenHAB",
 "description": "Graphs to display in Habpanel",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "job",
    "label": "Job",
    "query": "label_values(node_boot_time_seconds,job)"
   },
   {
    "name": "node",
    "label": "Host:",
    "query": "label_values(node_boot_time_seconds, instance)"
   },
   {
    "name": "port",
    "label": "Port",
    "query": "label_values(node_boot_time_seconds{instance=~\"$node:(.*)\"}, instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "Room Temperatures",
   "type": "graph",
   "description": "Temperature from room motion sensors",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "expr": "label_replace(openhab2_metric_number{name=~\"KNXMotion.*TemperatureCelcius\"} ,\"name\", \"$1\", \"name\", \"KNXMotion(.*)TemperatureCelcius\")\n",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Room Brightness",
   "type": "graph",
   "description": "Brightness from room motion sensors",
   "gridPos": { "h": 14, "w": 23, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "lux" }
   ],
   "targets": [
    {
     "expr": "label_replace(openhab2_metric_number{name=~\"KNXMotion.*BrightnessLux\"} ,\"name\", \"$1\", \"name\", \"KNXMotion(.*)BrightnessLux\")",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Electricity Costs",
   "type": "graph",
   "description": "Heating and general electricity costs based on 24h consumption.",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "currencyEUR" }
   ],
   "targets": [
    {
     "expr": "label_replace(increase(openhab2_metric_number{name=\"HousePowerCounter\"}[24h])/1000*0.26*30, \"name\", \"$1\", \"name\", \"(.*)PowerCounter\")",
     "legendFormat": "{{name}}"
    },
    {
     "expr": "label_replace(increase(openhab2_metric_number{name=\"HeatingPowerCounter\"}[24h])/1000*0.19*30, \"name\", \"$1\", \"name\", \"(.*)PowerCounter\")\n",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Cost Per Year",
   "type": "table-old",
   "description": "How much does it cost to run different devices per year. Averaged over the last 14 days. (electricity price=0.26/KWh)",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "label_replace(avg_over_time(openhab2_metric_number{instance=\"bunker.imagilan:9997\",job=\"openhab\",name=~\".*Hs110.*Power.*\"}[7d]), \"name\", \"$1\", \"name\", \".*Hs110(.*)_Power\")*24*365*0.26/1000",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Voltage monitoring",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "volt" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(openhab2_metric_number{instance=\"bunker.imagilan:9997\",job=\"openhab\",name=~\".*Voltage\"}[5m])",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "type": "graph",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 48 },
   "yaxes": [
    { "format": "watt" }
   ],
   "targets": [
    {
     "expr": "label_replace(openhab2_metric_number{instance=\"bunker.imagilan:9997\",job=\"openhab\",name=~\".*Hs110.*Power.*\"}, \"name\", \"$1\", \"name\", \".*Hs110(.*)_Power\")",
     "legendFormat": "{{name}}"
    }
   ]
  },
  { "title": "Volumes", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 60 } },
  {
   "title": "Audio Volumes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 61 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "openhab2_metric_dimmer{job=\"openhab\",name=~\".*Volume.*\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  { "title": "Basic Net / Disk Info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 69 } },
  {
   "title": "up/downstream",
   "type": "graph",
   "description": "Basic network info per interface",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 70 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "rate(node_network_receive_bytes_total{instance=\"w16gw.imagilan:9100\",job=~\"$job\",device=~\"ffvpn|eth0.4\"}[5m])",
     "legendFormat": "rx {{device}}"
    },
    {
     "expr": "rate(node_network_transmit_bytes_total{instance=\"w16gw.imagilan:9100\",job=~\"$job\",device=~\"ffvpn|eth0.4\"}[5m])",
     "legendFormat": "tx {{device}} "
    }
   ]
  },
  {
   "title": "wifi clients",
   "type": "graph",
   "description": "How many devices are connected",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 83 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sort_desc(count(wifi_station_tx_packets_total) by (ifname))",
     "legendFormat": "{{ifname}}"
    }
   ]
  }
 ]
}