{
 "title": "OpenHAB Items",
 "description": "OpenHAB Items",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "job",
    "label": "Job",
    "query": {
     "query": "label_values(node_boot_time_seconds,job)"
    }
   },
   {
    "name": "node",
    "label": "Host:",
    "query": {
     "query": "label_values(node_boot_time_seconds, instance)"
    }
   },
   {
    "name": "port",
    "label": "Port",
    "query": {
     "query": "label_values(node_boot_time_seconds{instance=~\"$node:(.*)\"}, instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Vitocal 200-S temperatures",
   "type": "graph",
   "gridPos": { "h": 28, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "expr": "label_replace(openhab2_metric_number{name=~\"KNXVitogate200.*temperature.*\"},\"name\", \"$1\", \"name\", \"KNXVitogate200(.*)\")",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Vitocal 200-S non-temperature values",
   "type": "graph",
   "gridPos": { "h": 28, "w": 24, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "label_replace(openhab2_metric_number{job=\"openhab\",name=~\"KNXVitogate200(.*)\",name!~\"(.*)temperature(.*)\"},\"name\", \"$1\", \"name\", \"KNXVitogate200(.*)\")",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Vitocal 200-S switches",
   "type": "heatmap",
   "gridPos": { "h": 36, "w": 24, "x": 0, "y": 56 },
   "targets": [
    {
     "expr": "label_replace(openhab2_metric_switch{name=~\"KNXVitogate200.*\"} ,\"name\", \"$1\", \"name\", \"KNXVitogate200(.*)\")",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "24h electricity cost",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 92 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(openhab2_metric_number{name=\"KNXPowerMeasurementsHousePowerWh\"}[24h])/1000*0.26"
    }
   ]
  },
  {
   "title": "24h heating cost",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 92 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(openhab2_metric_number{name=\"KNXPowerMeasurementsHeatingPowerWh\"}[24h])/1000*0.20"
    }
   ]
  },
  {
   "title": "Room Temperatures",
   "type": "graph",
   "description": "Temperature from room motion sensors",
   "gridPos": { "h": 22, "w": 24, "x": 0, "y": 100 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "expr": "label_replace(openhab2_metric_number{name=~\"KNXTemperatureCelcius.*\"} ,\"name\", \"$1\", \"name\", \"KNXTemperatureCelcius(.*)\")\n",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Heating Valve position",
   "type": "graph",
   "description": "0 = closed",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 122 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "label_replace(openhab2_metric_number{name=~\"KNXHeatingValveStatusPercentage.*\"} ,\"name\", \"$1\", \"name\", \"KNXHeatingValveStatusPercentage(.*)\")\n",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "KNX Bus Volts/mA",
   "type": "graph",
   "description": "KNX bus condition",
   "gridPos": { "h": 14, "w": 23, "x": 0, "y": 130 },
   "yaxes": [
    { "format": "volt" }
   ],
   "targets": [
    {
     "expr": "label_replace(openhab2_metric_number{name=~\"KNXPowerMeasurementsBus.*\"} ,\"name\", \"$1\", \"name\", \"KNXPowerMeasurementsBus(.*)\")\n",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "KNX Bus Traffic",
   "type": "graph",
   "gridPos": { "h": 14, "w": 23, "x": 0, "y": 144 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "label_replace(openhab2_metric_number{name=~\"KNXBusTraffic.*\"} ,\"name\", \"$1\", \"name\", \"KNXBusTraffic(.*)\")*100\n",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Presence",
   "type": "heatmap",
   "description": "Temperature from room motion sensors",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 158 },
   "targets": [
    {
     "expr": "label_replace(openhab2_metric_contact{name=~\"KNXMotionContact.*\"} ,\"name\", \"$1\", \"name\", \"KNXMotionContact(.*)\")\n",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Room Brightness",
   "type": "graph",
   "description": "Brightness from room motion sensors",
   "gridPos": { "h": 14, "w": 23, "x": 0, "y": 166 },
   "yaxes": [
    { "format": "lux" }
   ],
   "targets": [
    {
     "expr": "label_replace(openhab2_metric_number{name=~\"KNXLuminosityLux.*\"} ,\"name\", \"$1\", \"name\", \"KNXLuminosityLux(.*)\")",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Electricity Costs",
   "type": "graph",
   "description": "Heating and general electricity costs based on 24h consumption.",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 180 },
   "yaxes": [
    { "format": "currencyEUR" }
   ],
   "targets": [
    {
     "expr": "label_replace(increase(openhab2_metric_number{name=\"HousePowerCounter\"}[24h])/1000*0.26*30, \"name\", \"$1\", \"name\", \"(.*)PowerCounter\")",
     "legendFormat": "{{name}}"
    },
    {
     "expr": "label_replace(increase(openhab2_metric_number{name=\"HeatingPowerCounter\"}[24h])/1000*0.19*30, \"name\", \"$1\", \"name\", \"(.*)PowerCounter\")\n",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Cost Per Year",
   "type": "table-old",
   "description": "How much does it cost to run different devices per year. Averaged over the last 14 days. (electricity price=0.26/KWh)",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 190 },
   "targets": [
    {
     "expr": "label_replace(avg_over_time(openhab2_metric_number{instance=\"bunker.imagilan:9997\",job=\"openhab\",name=~\".*Hs110.*Power.*\"}[7d]), \"name\", \"$1\", \"name\", \".*Hs110(.*)_Power\")*24*365*0.26/1000",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Voltage monitoring",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 198 },
   "yaxes": [
    { "format": "volt" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(openhab2_metric_number{instance=\"bunker.imagilan:9997\",job=\"openhab\",name=~\".*Voltage\"}[5m])",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "type": "graph",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 206 },
   "yaxes": [
    { "format": "watt" }
   ],
   "targets": [
    {
     "expr": "label_replace(openhab2_metric_number{instance=\"bunker.imagilan:9997\",job=\"openhab\",name=~\".*Hs110.*Power.*\"}, \"name\", \"$1\", \"name\", \".*Hs110(.*)_Power\")",
     "legendFormat": "{{name}}"
    }
   ]
  },
  { "title": "Volumes", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 218 } },
  {
   "title": "Audio Volumes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 219 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "label_replace(openhab2_metric_dimmer{job=\"openhab\",name=~\".*Volume.*\"},\"name\", \"$1\", \"name\", \"ChromecastAudio(.*)Volume\")",
     "legendFormat": "{{name}}"
    }
   ]
  },
  { "title": "Basic Net / Disk Info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 227 } },
  {
   "title": "up/downstream",
   "type": "graph",
   "description": "Basic network info per interface",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 228 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "rate(node_network_receive_bytes_total{instance=\"w16gw.imagilan:9100\",job=~\"$job\",device=~\"ffvpn|eth0.4\"}[5m])",
     "legendFormat": "rx {{device}}"
    },
    {
     "expr": "rate(node_network_transmit_bytes_total{instance=\"w16gw.imagilan:9100\",job=~\"$job\",device=~\"ffvpn|eth0.4\"}[5m])",
     "legendFormat": "tx {{device}} "
    }
   ]
  },
  {
   "title": "wifi clients",
   "type": "graph",
   "description": "How many devices are connected",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 241 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sort_desc(count(wifi_station_tx_packets_total) by (ifname))",
     "legendFormat": "{{ifname}}"
    }
   ]
  }
 ]
}